import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import { GoogleLogin } from "react-google-login";
import {
  googleLogout,
  TokenResponse,
  useGoogleLogin,
} from "@react-oauth/google";
import axios from "axios";
import { userInfo } from "os";

export default function Home() {
  const router = useRouter();

 

  return (
    <div className={styles.container}>
      <Head>
        <title>Graphql</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Graph Ql</a>
        </h1>
        <div className="mt-9">
          <button
            className="p-2 w-48 bg-slate-50 text-black  border-2  "
            onClick={() => {
              router.push("/login");
            }}
          >
            Login
          </button>
          <button
            className="p-2  w-48 border-2  border-white"
            onClick={() => {
              router.push("/signup");
            }}
          >
            Signup
          </button>
         
          ,
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
          <span className="p-3 mb-0.5 text-purple-500">and GrpahQl</span>
        </a>
      </footer>
    </div>
  );
}
